export function getUI() {
  const byId = id => document.getElementById(id);
  const pauseScreen = byId('pauseScreen');
  return {
    canvas: byId('game'),
    hudEl: byId('hud'),
    heartsEl: byId('hearts'),
    dashStatusEl: byId('dashStatus'),
    controlsEl: byId('controls'),
    messageEl: byId('message'),
    messageTitleEl: byId('messageTitle'),
    startScreen: byId('startScreen'),
    startButton: byId('startButton'),
    startSettingsButton: byId('startSettingsButton'),
    resumeButton: byId('resumeButton'),
    restartButton: byId('restartButton'),
    mainMenuButton: byId('mainMenuButton'),
    settingsButton: byId('settingsButton'),
    pauseScreen,
    menuEyebrow: byId('menuEyebrow'),
    menuTitle: byId('menuTitle'),
    menuPages: byId('menuPages'),
    pauseMain: byId('pauseMainPage'),
    pauseMainPage: byId('pauseMainPage'),
    settingsPage: byId('settingsPage'),
    controlsPage: byId('controlsPage'),
    advancedPage: byId('advancedPage'),
    motionButtons: [...document.querySelectorAll('[data-motion]')],
    motionStatus: byId('motionStatus'),
    controlsNavButton: byId('controlsNavButton'),
    advancedNavButton: byId('advancedNavButton'),
    settingsBackButton: byId('settingsBackButton'),
    controlsBackButton: byId('controlsBackButton'),
    advancedBackButton: byId('advancedBackButton'),
    bindStatus: byId('bindStatus'),
    bindList: byId('bindList'),
    editKeyboardButton: byId('editKeyboardButton'),
    editControllerButton: byId('editControllerButton'),
    controllerEnabled: byId('controllerEnabled'),
    developerMode: byId('developerMode'),
    developerTools: byId('developerTools'),
    settingsJson: byId('settingsJson'),
    dumpSettingsButton: byId('dumpSettingsButton'),
    replaceSettingsButton: byId('replaceSettingsButton'),
    settingsJsonStatus: byId('settingsJsonStatus'),
    controllerName: byId('controllerName'),
    controllerInputs: byId('controllerInputs'),
    controllerStatus: byId('controllerStatus'),
    resetBindsButton: byId('resetBindsButton')
  };
}
