export function getUI() {
  const byId = id => document.getElementById(id);
  const pauseScreen = byId('pauseScreen');
  return {
    canvas: byId('game'),
    hudEl: byId('hud'),
    hudLevelName: byId('hudLevelName'),
    heartsEl: byId('hearts'),
    dashStatusEl: byId('dashStatus'),
    controlsEl: byId('controls'),
    messageEl: byId('message'),
    messageTitleEl: byId('messageTitle'),
    messageNextLevelButton: byId('messageNextLevelButton'),
    messageLevelSelectButton: byId('messageLevelSelectButton'),
    messageRestartButton: byId('messageRestartButton'),
    startScreen: byId('startScreen'),
    startButton: byId('startButton'),
    startSettingsButton: byId('startSettingsButton'),
    startLevelSelectButton: byId('startLevelSelectButton'),
    selectedLevelSummary: byId('selectedLevelSummary'),
    resumeButton: byId('resumeButton'),
    restartButton: byId('restartButton'),
    mainMenuButton: byId('mainMenuButton'),
    settingsButton: byId('settingsButton'),
    levelSelectButton: byId('levelSelectButton'),
    pauseScreen,
    menuEyebrow: byId('menuEyebrow'),
    menuTitle: byId('menuTitle'),
    menuPages: byId('menuPages'),
    pauseMain: byId('pauseMainPage'),
    pauseMainPage: byId('pauseMainPage'),
    levelSelectPage: byId('levelSelectPage'),
    levelSelectList: byId('levelSelectList'),
    levelSelectStatus: byId('levelSelectStatus'),
    levelSelectBackButton: byId('levelSelectBackButton'),
    settingsHubPage: byId('settingsHubPage'),
    settingsCategoryPage: byId('settingsCategoryPage'),
    settingsRootRows: byId('settingsRootRows'),
    settingsCategoryList: byId('settingsCategoryList'),
    settingsCategoryDescription: byId('settingsCategoryDescription'),
    settingsStatus: byId('settingsStatus'),
    settingsCategoryBody: byId('settingsCategoryBody'),
    settingsBackButton: byId('settingsBackButton'),
    settingsCategoryBackButton: byId('settingsCategoryBackButton'),
    settingsJson: byId('settingsJson'),
    dumpSettingsButton: byId('dumpSettingsButton'),
    replaceSettingsButton: byId('replaceSettingsButton'),
    settingsJsonStatus: byId('settingsJsonStatus'),
    developerTools: byId('developerTools'),
    controllerName: byId('controllerName'),
    controllerInputs: byId('controllerInputs'),
    controllerStatus: byId('controllerStatus')
  };
}
