export function getUI() {
  const byId = id => document.getElementById(id);
  const pauseScreen = byId('pauseScreen');
  return {
    canvas: byId('game'),
    hudEl: byId('hud'),
    heartsEl: byId('hearts'),
    dashStatusEl: byId('dashStatus'),
    controlsEl: byId('controls'),
    messageEl: byId('message'),
    messageTitleEl: byId('messageTitle'),
    startScreen: byId('startScreen'),
    startButton: byId('startButton'),
    startSettingsButton: byId('startSettingsButton'),
    resumeButton: byId('resumeButton'),
    restartButton: byId('restartButton'),
    mainMenuButton: byId('mainMenuButton'),
    settingsButton: byId('settingsButton'),
    pauseScreen,
    menuEyebrow: byId('menuEyebrow'),
    menuTitle: byId('menuTitle'),
    menuPages: byId('menuPages'),
    pauseMain: byId('pauseMainPage'),
    pauseMainPage: byId('pauseMainPage'),
    settingsHubPage: byId('settingsHubPage'),
    settingsCategoryPage: byId('settingsCategoryPage'),
    settingsRootRows: byId('settingsRootRows'),
    settingsCategoryList: byId('settingsCategoryList'),
    settingsCategoryDescription: byId('settingsCategoryDescription'),
    settingsStatus: byId('settingsStatus'),
    settingsCategoryBody: byId('settingsCategoryBody'),
    settingsBackButton: byId('settingsBackButton'),
    settingsCategoryBackButton: byId('settingsCategoryBackButton'),
    settingsJson: byId('settingsJson'),
    dumpSettingsButton: byId('dumpSettingsButton'),
    replaceSettingsButton: byId('replaceSettingsButton'),
    settingsJsonStatus: byId('settingsJsonStatus'),
    developerTools: byId('developerTools'),
    controllerName: byId('controllerName'),
    controllerInputs: byId('controllerInputs'),
    controllerStatus: byId('controllerStatus')
  };
}
